### ISSUE TITLE
Callbacks are not supported

### ISSUE THREAD

**Issue by Christoph-Wagner** [typpo/quickchart#2]
This makes it impossible to customize the autogenerated ticks. In my case I wanted to add digit grouping.
Here is a small example
```
{
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [
      {
        label: 'Dogs',
        backgroundColor: 'chartreuse',
        data: [50, 60, 70, 180, 190]
      },
      {
        label: 'Cats',
        backgroundColor: 'gold',
        data: [100, 200, 300, 400, 500]
      }
    ]
  },
  options: {
    scales: {
      yAxes: [
        {
          stacked: true,
          ticks: {
            callback: function(value) {
              return value;
            }
          }
        }
      ]
    }
  }
}
```

Removing the callback part:

```
 ticks: {
            callback: function(value) {
              return value;
            }
          }
```

fixes it.

I understand not wanting to run user JS on your server, but afaik this is the only way to customize ticks in chart.js

**Comment by typpo** [comment]
Hi Christoph, thanks for bringing this up.  I'm looking into options for rendering the chart in a sandboxed environment and allowing Javascript.

This was one of the downsides of choosing Chart.js.  A declarative graph library like [Vega](https://vega.github.io/vega/) would be a perfect fit, but I chose Chart.js because it is very popular, documentation and examples are plentiful, and it is easy to use.  Vega is very flexible but also quite verbose.  Unfortunately the "js" in Chart.js provides a challenge.

**Comment by typpo** [comment]
Good news, I've made a change to allow callbacks.  Your example now works (I added a dollar sign to the ticks to make the change more obvious):

![image](https://user-images.githubusercontent.com/310310/54223794-7ee1b000-44b5-11e9-954f-25d798d61337.png)
[Link to graph on QuickChart.io](https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27January%27%2C%20%27February%27%2C%20%27March%27%2C%20%27April%27%2C%20%27May%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27Dogs%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27chartreuse%27%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B50%2C%2060%2C%2070%2C%20180%2C%20190%5D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27Cats%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27gold%27%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B100%2C%20200%2C%20300%2C%20400%2C%20500%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20yAxes%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20stacked%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20callback%3A%20function(value)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%27%24%27%20%2B%20value%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

```
{
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [
      {
        label: 'Dogs',
        backgroundColor: 'chartreuse',
        data: [50, 60, 70, 180, 190]
      },
      {
        label: 'Cats',
        backgroundColor: 'gold',
        data: [100, 200, 300, 400, 500]
      }
    ]
  },
  options: {
    scales: {
      yAxes: [
        {
          stacked: true,
          ticks: {
            callback: function(value) {
              return '$' + value;
            }
          }
        }
      ]
    }
  }
}
```

**Comment by Christoph-Wagner** [comment]
Wonderful, that works flawlessly, thanks :)

**Comment by choychris** [comment]
@typpo Thanks for your effort and open-sourcing such a useful project.
I would like to format label in doughnut chart, however I cannot get it to work with the following code:
```
let chartConfig = {
    type:'doughnut',
    data:{
        labels:['January','February','March','April', 'May'],
        datasets:[{
            data:[50,60,70,180,190],
            backgroundColor: [
                "rgb(26,225,183)",
                "rgb(242,126,28)",
                "rgb(242,203,28)",
                "rgb(255,68,112)",
                "rgb(111,123,255)",
            ]
        }]
    },
    options:{
        layout: {
            padding: {left: 10, top: 20, bottom: 20}
        },
        cutoutPercentage: 60,
        legend:{
            position:'left', 
            labels: {boxWidth:30, usePointStyle:true, fontSize: 16, padding: 16}
        },
        plugins: {
            datalabels: {
                font: {
                   size:10
                },
                anchor: 'end',
                align: 'end',
                formatter: "function(val, ctx){return val + '%';}"
            }
        }
    }
}
// console.log(chartConfig)
let getChartUrl = "https://quickchart.io/chart?c=" + JSON.stringify(chartConfig);
console.log(getChartUrl.replace(/\"function/g, 'function').replace(/;}\"/g, ';}'));
```
If I remove `formatter: "function(val, ctx){return val + '%';}"`, it works perfectly. May I know the reason ?

Any help is very much appreciated.

**Comment by typpo** [comment]
Hi @choychris,

Two problems here:

1) Because you are request a complex config, be sure to URI encode your request via `encodeURIComponent(JSON.stringify(chartConfig))`

2) `formatter` is expected to be a function, not a string.  So remove the double quotes:

```
                formatter: function(val, ctx){return val + '%';}
```

Those two corrections render this chart properly ([link](https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20%20%20type%3A%27doughnut%27%2C%0A%20%20%20%20data%3A%7B%0A%20%20%20%20%20%20%20%20labels%3A%5B%27January%27%2C%27February%27%2C%27March%27%2C%27April%27%2C%20%27May%27%5D%2C%0A%20%20%20%20%20%20%20%20datasets%3A%5B%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20data%3A%5B50%2C60%2C70%2C180%2C190%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22rgb(26%2C225%2C183)%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22rgb(242%2C126%2C28)%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22rgb(242%2C203%2C28)%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22rgb(255%2C68%2C112)%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22rgb(111%2C123%2C255)%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20options%3A%7B%0A%20%20%20%20%20%20%20%20layout%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20padding%3A%20%7Bleft%3A%2010%2C%20top%3A%2020%2C%20bottom%3A%2020%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20cutoutPercentage%3A%2060%2C%0A%20%20%20%20%20%20%20%20legend%3A%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%27left%27%2C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20labels%3A%20%7BboxWidth%3A30%2C%20usePointStyle%3Atrue%2C%20fontSize%3A%2016%2C%20padding%3A%2016%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20plugins%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A10%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20anchor%3A%20%27end%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20align%3A%20%27end%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20formatter%3A%20function(val%2C%20ctx)%7Breturn%20val%20%2B%20%27%25%27%3B%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)):
![choychris chart image](https://user-images.githubusercontent.com/310310/54933143-51dfc500-4ed9-11e9-87fc-b70b6692635e.png)

As an aside, your question helped me notice a problem with Express automatically replacing + with a space.  I fixed that problem in 65e142223fc78a40f7919e3703bd99d5b02a0da2.  Thanks!

**Comment by choychris** [comment]
Awesome! It finally works with encodeURIComponent(). Thank you so much for your help.
Love this library. Just see that there is a docker image too. This is super cool. 

Thanks again for such an effort of making quickchart.

**Comment by orouz** [comment]
hey @typpo 

great lib, thanks for putting the effort! 

i see others managed to get it working but it's still unclear to me how.
because `JSON.stringify` removes any non serialisable properties, like functions.

so essentially this: 
```const config = { callback: function() { return "whatever" }}```
```const data = encodeURIComponent(JSON.stringify(config))```

results in this: `%7B%7D` which decodes to `{}`

could you provide an example on how to send the data with callbacks? 
i also copy-pasted @choychris code and modified it as per your comments yet still no dice 😐 

thanks again for such a cool and useful project!

**Comment by typpo** [comment]
Hey @orouz, it looks like my previous advice was not fully correct as `JSON.stringify` will break functions.  Essentially, we want to send the full Chart.js config, including Javascript, as a string.

The question is, how can we construct that Chart.js config string?  A few options:

  1.  Just build the config as a string.  This is the most straightforward way:

```
const chartStr = `{
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [{
      label: 'Dogs',
      data: [ 50, 60, 70, 180, 190 ]
    }]
  },
  options: {
    scales: {
      yAxes: [{
        ticks: {
          callback: function(value) {
            return '$' + value;
          }
        }
      }],
    },
  },
}`;

console.log(encodeURIComponent(chartStr));
```

  2.  The string approach makes it more difficult to build and modify the object.  Another option is to construct it in object format excluding the functions, and then substitute the functions later:

```
const chartObj = {
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [{
      label: 'Dogs',
      data: [ 50, 60, 70, 180, 190 ]
    }]
  },
  options: {
    scales: {
      yAxes: [{
        ticks: {
          callback: '{{CALLBACK_PLACEHOLDER}}',
        }
      }],
    },
  },
};

// ... modify chartObj as a normal javascript object ...

const chartStr = JSON.stringify(chartObj).replace('"{{CALLBACK_PLACEHOLDER}}"', 'function(value) { return "$" + value }');

console.log(encodeURIComponent(chartStr));
```

  3. Unfortunately the above is a bit ugly.  You can make it all happen neatly by using a library like [javascript-stringify](https://github.com/blakeembrey/javascript-stringify):

```
const { stringify } = require('javascript-stringify');

const chartObj = {
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [{
      label: 'Dogs',
      data: [ 50, 60, 70, 180, 190 ]
    }]
  },
  options: {
    scales: {
      yAxes: [{
        ticks: {
          callback: function(value) {
            return '$' + value;
          }
        }
      }],
    },
  },
};

console.log(encodeURIComponent(stringify(chartObj)));
```

**Comment by orouz** [comment]
thanks @typpo ! 

i think this can be closed now.

**Comment by vgutkovsky** [comment]
Sorry to reopen the thread. I'm not sure if something changed, but I'm literally trying the exact example from above and am getting an error: Syntax error: Unexpected Identifier. I'm just pasting the below into Chrome.

http://quickchart.io/chart?width=600&height=400&c={
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [
      {
        label: 'Dogs',
        backgroundColor: 'chartreuse',
        data: [50, 60, 70, 180, 190]
      },
      {
        label: 'Cats',
        backgroundColor: 'gold',
        data: [100, 200, 300, 400, 500]
      }
    ]
  },
  options: {
    scales: {
      yAxes: [
        {
          stacked: true,
          ticks: {
            callback: function(value) {
              return '$' + value;
            }
          }
        }
      ]
    }
  }
}

**Comment by typpo** [comment]
Hey @vgutkovsky, try URL-encoding it before pasting in Chrome.  In this case it seems like the `+` in your function is being interpreted as a space in the query component part of the URL.  You can encode `+` as `%2B` or just encode the entire URL (almost every programming language has something that can do this).

Here's a [direct link](https://quickchart.io/chart?bkg=white&c=%7B%0Atype%3A%20%27bar%27%2C%0Adata%3A%20%7B%0Alabels%3A%20%5B%27January%27%2C%20%27February%27%2C%20%27March%27%2C%20%27April%27%2C%20%27May%27%5D%2C%0Adatasets%3A%20%5B%0A%7B%0Alabel%3A%20%27Dogs%27%2C%0AbackgroundColor%3A%20%27chartreuse%27%2C%0Adata%3A%20%5B50%2C%2060%2C%2070%2C%20180%2C%20190%5D%0A%7D%2C%0A%7B%0Alabel%3A%20%27Cats%27%2C%0AbackgroundColor%3A%20%27gold%27%2C%0Adata%3A%20%5B100%2C%20200%2C%20300%2C%20400%2C%20500%5D%0A%7D%0A%5D%0A%7D%2C%0Aoptions%3A%20%7B%0Ascales%3A%20%7B%0AyAxes%3A%20%5B%0A%7B%0Astacked%3A%20true%2C%0Aticks%3A%20%7B%0Acallback%3A%20function(value)%20%7B%0Areturn%20%27%24%27%20%2B%20value%3B%0A%7D%0A%7D%0A%7D%0A%5D%0A%7D%0A%7D%0A%7D) to the URL-encoded version

**Comment by vgutkovsky** [comment]
Ah, thank you, %2B did indeed work!
