### ISSUE TITLE
Error with Xibo

### ISSUE THREAD

**Issue by 1TF0rward** [typpo/quickchart#39]
Hi,

When updating to the latest Xibo I get errors with quickchart.

"yarn run v1.19.1
$ node index.js
error Command failed with signal “SIGSEGV”.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."

and

"xibo_cms-quickchart exited with code 1"

There has been a thread created on the Xibo forums pointing us to here to report this. (https://community.xibo.org.uk/t/issue-with-ianw-quickchart/21491/2)
I have tried using an older version but this doesn't let Xibo start.

Any help would be great.

**Comment by typpo** [comment]
Hi @1TF0rward, I need a little more info here.  Can you tell me about the machine specs/operating system you're running on?  Is it possible, for example, that it's running out of memory?

**Comment by 1TF0rward** [comment]
Hi,

It's an Ubuntu virtual machine with dynamic ram currently at 2GB but if it needs it can go up quite a bit. It also has 1 virtual processor.

**Comment by typpo** [comment]
It's a little hard to say.  Are you running this in a docker container?

I'm guessing the crash is related to some of the Cairo/Pango/jpeg system dependencies.  Maybe machine hardware is a factor.

Otherwise the only idea I have is to release a version with the segfault-handler package and try to get more useful debug output.

**Comment by typpo** [comment]
Closing this for now.  Let me know if you have more details!
