### ISSUE TITLE
Feature Request: Default Colors in Chart API Parameters?

### ISSUE THREAD

**Issue by prettycode** [typpo/quickchart#49]
Any chance we could get the default color wheel that's set in `/lib/charts.js` to be configurable? For example, the Chart API Parameters for quickchart.io takes `chart`, `height`, `width`, etc. Would be great if there was a `defaultColors` setting!

That `charts.js` has some very useful code in it to figure out how to intelligently apply the `DEFAULT_COLORS` colors based on different chart types. We'd love to take advantage of that code by passing into the Chart API Parameters a custom palette that's an alternative to `DEFAULT_COLORS`. Looks like `renderChart()` would have another parameter that comes from the (proposed) Chart API Parameter `defaultColors` setting.

Currently, without this option, if we have 20 different charts we render through quickchart.io and have a single color palette we want all those charts to use, it means setting those colors manually in each of the 20 different ChartJS `chart` configs. Not the end of the world, but adds risk.

**Comment by typpo** [comment]
This is a decent suggestion - I should have an experimental feature available shortly

**Comment by typpo** [comment]
Sorry this took so long.  I wound up taking a different approach because I wasn't happy with the custom behavior of my pull request.

I added support for the [chartjs-plugin-colorschmes](https://nagix.github.io/chartjs-plugin-colorschemes) plugin.  You can see the full list of colorschemes [here](https://nagix.github.io/chartjs-plugin-colorschemes/colorchart.html).

Example using Tableau colorscheme:
```
{
  type: 'bar',
  data: {
    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
    datasets: [{
      label: 'Data1',
      data: [50, 60, 70, 180]
    }, {
      label: 'Data2',
      data: [30, 60, 70, 150]
    }, {
      label: 'Data3',
      data: [50, 50, 60, 130]
    }, {
      label: 'Data4',
      data: [40, 70, 100, 100]
    },{
      label: 'Data5',
      data: [60, 80, 80, 190]
    }]
  },
  options: {
    plugins: {
      colorschemes: {
        scheme: 'tableau.Tableau10'
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/310310/85927695-9dabb780-b85c-11ea-9e15-ff796bb4e223.png)

You can also set your own scheme, e.g.:
```
  options: {
    plugins: {
      colorschemes: {
        scheme: ['red', 'green', 'blue', 'orange', 'pink'],
      }
    }
  }
```

Hope this helps a bit.

**Comment by prettycode** [comment]
This is way cool. Thanks so much for your time and effort that you put into this, Ian! Very much appreciated and think you came to a great resolution.
