### ISSUE TITLE
image size is doubled what is specified

### ISSUE THREAD

**Issue by randallt** [typpo/quickchart#5]
When I specify an image size using the w and h URL parameters, the resulting image always seems to be double.

For example, 
https://quickchart.io/chart?w=200&h=100&c={type:%27line%27,data:{datasets:[{data:[50,60,70,180,190]}]}}

Results in an image that is 400x200.

**Comment by typpo** [comment]
This happens because the charts are rendered for retina displays, where the device pixel ratio is 2x.  So the images are 2x in actual pixels but they are meant to be sized to 200x100 (in your example) for retina viewing.

Obviously this is a bit confusing for people who don't care about retina displays.  I will figure out a better approach and update this issue.

**Comment by typpo** [comment]
There is now a `devicePixelRatio` parameter than can be set to `1.0` to achieve desired non-retina behavior.
