### ISSUE TITLE
docker image encoding chinese incorrectly

### ISSUE THREAD

**Issue by xuzhen1994** [typpo/quickchart#59]
relates to
#8 

![image](https://user-images.githubusercontent.com/6793111/82898077-3c59a580-9f8b-11ea-8028-76bf5c796fc1.png)

**Comment by typpo** [comment]
I am able to render "好的" as a label in the latest container.  I'm thinking that maybe it's because you are running an older version of the container without updated fonts due to your other issue #29 

Just to confirm, the URL below doesn't work for you in a container running v1.2?

http://localhost:3400/chart?bkg=white&c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B2012%2C%202013%2C%202014%2C%202015%2C%202016%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20label%3A%20%27%E5%A5%BD%E7%9A%84%27%2C%0A%20%20%20%20%20%20data%3A%20%5B12%2C%206%2C%205%2C%2018%2C%2012%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20label%3A%20%27Bananas%27%2C%0A%20%20%20%20%20%20data%3A%20%5B4%2C%208%2C%2016%2C%205%2C%205%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%0A%7D

**Comment by xuzhen1994** [comment]
I've changed my docker version and repulled the latest image. Now i can run the latest version of image on my server, but the chinese character doesn't work.
![image](https://user-images.githubusercontent.com/6793111/82970597-369fa680-a003-11ea-9e54-d8e340f3953d.png)

The url you provide doesn't work for me in V1.3
![image](https://user-images.githubusercontent.com/6793111/82971146-98144500-a004-11ea-9a72-30fc20c7a89d.png)

**Comment by xuzhen1994** [comment]
I dive the latest docker image and it contains noto font, so maybe my host server need some extra config?
![image](https://user-images.githubusercontent.com/6793111/82972060-baa75d80-a006-11ea-8ac7-a1683985ee6e.png)

**Comment by typpo** [comment]
Thanks for looking into this.  I think it's because the Docker image is out of date!  In particular, it is missing this line that installs Chinese fonts: https://github.com/typpo/quickchart/blob/master/Dockerfile#L10

I just packaged and released v1.4.0.  Could you give it a try with the new image and see if that solves your problem?

**Comment by xuzhen1994** [comment]
got an error when run the latest image.

> [root@localhost ~]# docker run ianw/quickchart
Stackdriver logging is disabled
{"name":"quickchart","hostname":"814783c4ab6a","pid":1,"level":30,"msg":"Loaded 6 keys from API keyfile","time":"2020-05-28T02:05:20.294Z","v":0}
{"name":"quickchart","hostname":"814783c4ab6a","pid":1,"level":30,"msg":"Telemetry is enabled","time":"2020-05-28T02:05:20.490Z","v":0}
/quickchart/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
  ^
Error: 
Something went wrong installing the "sharp" module
Error relocating /quickchart/node_modules/sharp/build/Release/../../vendor/lib/libvips.so.42: g_date_time_format_iso8601: symbol not found
- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues
    at Object.<anonymous> (/quickchart/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/quickchart/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by typpo** [comment]
I've just published a new v1.4.0 docker image that fixes the `sharp`-related crash on startup.  Could you please give it one more try?

**Comment by xuzhen1994** [comment]
I tried it again, and it works fine. Thanks a lot.
