### ISSUE TITLE
Translation of timeseries axis

### ISSUE THREAD

**Issue by cheerfulstoic** [typpo/quickchart#93]
It is, of course, possible to translate labels on axes in quickchart if you define them yourself, but when using date/times as the X axis, for example, I believe that the labels come from quickchart itself:

<img width="511" alt="Screenshot 2021-05-31 at 11 30 57" src="https://user-images.githubusercontent.com/301415/120172905-cd4d0780-c203-11eb-97a6-f67493f007e9.png">

Is there a configuration which could define what labels are used?  Maybe a configuration that would allow you to define a custom mapping of month names?  If not, do you think it would be difficult to implement (thinking in terms of submitting a PR)

**Comment by cheerfulstoic** [comment]
I see that you use Chart.js under the covers.  Maybe this would be an easy way to support internationalization of date/times?

https://stackoverflow.com/questions/34385952/does-the-chartjs-supports-localization

**Comment by typpo** [comment]
Hi @cheerfulstoic, it turns out you can do this using a callback and `Date. toLocaleDateString` ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)).

You can do this with the `ticks.callback` function:
```js
    "scales": {
      "xAxes": [{
        "type": "time",
        // ...
        "ticks": {
          "callback": function(val) {
            return new Date(val).toLocaleDateString('sv-SE');  
          },
        },
      }],
```

Here's a live example in the chart sandbox: [link](https://quickchart.io/sandbox/#%7B%0A%20%20%22type%22%3A%20%22line%22%2C%0A%20%20%22data%22%3A%20%7B%0A%20%20%20%20%22labels%22%3A%20%5B%0A%20%20%20%20%20%20new%20Date(%222020-06-14T16%3A08%3A20.288Z%22)%2C%0A%20%20%20%20%20%20new%20Date(%222020-06-15T16%3A08%3A20.288Z%22)%2C%0A%20%20%20%20%20%20new%20Date(%222020-06-16T16%3A08%3A20.289Z%22)%2C%0A%20%20%20%20%20%20new%20Date(%222020-06-17T16%3A08%3A20.289Z%22)%2C%0A%20%20%20%20%20%20new%20Date(%222020-06-18T16%3A08%3A20.289Z%22)%2C%0A%20%20%20%20%20%20new%20Date(%222020-06-19T16%3A08%3A20.289Z%22)%2C%0A%20%20%20%20%20%20new%20Date(%222020-06-20T16%3A08%3A20.289Z%22)%0A%20%20%20%20%5D%2C%0A%20%20%20%20%22datasets%22%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22label%22%3A%20%22My%20First%20dataset%22%2C%0A%20%20%20%20%20%20%20%20%22backgroundColor%22%3A%20%22rgba(255%2C%2099%2C%20132%2C%200.5)%22%2C%0A%20%20%20%20%20%20%20%20%22borderColor%22%3A%20%22rgb(255%2C%2099%2C%20132)%22%2C%0A%20%20%20%20%20%20%20%20%22fill%22%3A%20false%2C%0A%20%20%20%20%20%20%20%20%22data%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%2038%2C%0A%20%20%20%20%20%20%20%20%20%20-19%2C%0A%20%20%20%20%20%20%20%20%20%2035%2C%0A%20%20%20%20%20%20%20%20%20%20-2%2C%0A%20%20%20%20%20%20%20%20%20%2077%2C%0A%20%20%20%20%20%20%20%20%20%2078%2C%0A%20%20%20%20%20%20%20%20%20%20-93%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22label%22%3A%20%22My%20Second%20dataset%22%2C%0A%20%20%20%20%20%20%20%20%22backgroundColor%22%3A%20%22rgba(54%2C%20162%2C%20235%2C%200.5)%22%2C%0A%20%20%20%20%20%20%20%20%22borderColor%22%3A%20%22rgb(54%2C%20162%2C%20235)%22%2C%0A%20%20%20%20%20%20%20%20%22fill%22%3A%20false%2C%0A%20%20%20%20%20%20%20%20%22data%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%2018%2C%0A%20%20%20%20%20%20%20%20%20%20-7%2C%0A%20%20%20%20%20%20%20%20%20%2049%2C%0A%20%20%20%20%20%20%20%20%20%2086%2C%0A%20%20%20%20%20%20%20%20%20%2063%2C%0A%20%20%20%20%20%20%20%20%20%20-92%2C%0A%20%20%20%20%20%20%20%20%20%20-35%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22label%22%3A%20%22Dataset%20with%20point%20data%22%2C%0A%20%20%20%20%20%20%20%20%22backgroundColor%22%3A%20%22rgba(75%2C%20192%2C%20192%2C%200.5)%22%2C%0A%20%20%20%20%20%20%20%20%22borderColor%22%3A%20%22rgb(75%2C%20192%2C%20192)%22%2C%0A%20%20%20%20%20%20%20%20%22fill%22%3A%20false%2C%0A%20%20%20%20%20%20%20%20%22data%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22x%22%3A%20%2206%2F14%2F2020%2009%3A08%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22y%22%3A%20-29%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22x%22%3A%20%2206%2F19%2F2020%2009%3A08%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22y%22%3A%20-34%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22x%22%3A%20%2206%2F21%2F2020%2009%3A08%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22y%22%3A%20-62%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22x%22%3A%20%2206%2F29%2F2020%2009%3A08%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22y%22%3A%201%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%22options%22%3A%20%7B%0A%20%20%20%20%22title%22%3A%20%7B%0A%20%20%20%20%20%20%22text%22%3A%20%22Chart.js%20Time%20Scale%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22scales%22%3A%20%7B%0A%20%20%20%20%20%20%22xAxes%22%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%22type%22%3A%20%22time%22%2C%0A%20%20%20%20%20%20%20%20%22time%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22parser%22%3A%20%22MM%2FDD%2FYYYY%20HH%3Amm%22%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22scaleLabel%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22display%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%22labelString%22%3A%20%22Date%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22ticks%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22callback%22%3A%20function(val)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20new%20Date(val).toLocaleDateString('sv-SE')%3B%20%20%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%5D%2C%0A%20%20%20%20%20%20%22yAxes%22%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%22scaleLabel%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22display%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%22labelString%22%3A%20%22value%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

Hope this helps!
